### ISSUE TITLE
Hi! 

### ISSUE THREAD

**Issue by ylichadeev** [chipset95/Potato-Library#5]
https://jitpack.io/com/github/kartikarora/Potato-Library/0.1.6/build.log  

Can u fix build 0.1.6?

And add `return pref.contains(preferenceName)` method in next release?

**Comment by kartikarora** [comment]
@needsst I'm aware of the build failure and jitpack seems to be not working right now! Will add the contains method soon! Else, feel free to send a pull request!

**Comment by jyotman** [comment]
@kartikarora may I take up the `contains()` method issue and submit a pull request?

**Comment by kartikarora** [comment]
@jyotman94 sure! Go ahead!

**Comment by kartikarora** [comment]
@needsst `0.1.6` build fixed!

**Comment by kartikarora** [comment]
@needsst Releasing the changes now!
