### ISSUE TITLE
Usage of Toast inside Utils

### ISSUE THREAD

**Issue by jyotman** [chipset95/Potato-Library#7]
Some of the methods inside the Utils class like `isBluetoothAvailable()` show a Toast. I think this should not forced onto the developer using the library as he might not want to show a Toast to the user and handle it in some other way. 
Another way could be that the method could take a flag to show the toast.

What do you think?

**Comment by kartikarora** [comment]
@jyotman94 Seems like a good idea to me, returning a boolean is good enough, the developer can then choose his own way of representing the issue!

**Comment by jyotman** [comment]
Cool! I'll submit a PR soon.
