### ISSUE TITLE
Repository problems

### ISSUE THREAD

**Issue by lossurdo** [chipset95/Potato-Library#9]
Dependency has not been found in repository. Here is the Android Studio compiling message:

```
Error:Could not find potato.jar (me.kartikarora.potato:potato:0.2.0).
Searched in the following locations:
    https://jcenter.bintray.com/me/kartikarora/potato/potato/0.2.0/potato-0.2.0.jar
```
There is no JAR file in:
https://jcenter.bintray.com/me/kartikarora/potato/potato/0.2.0/

**Comment by kartikarora** [comment]
Thanks for pointing this out. I'll look at it asap. My machine has gone a little wonky, so please give me some time, I'll definitely fix this though.

**Comment by kartikarora** [comment]
@lossurdo Its fixed now! Apologies for the delay! There's a slight change in the artifact name, and it will be available on jcenter in a short period of time. 

It is available on `https://dl.bintray.com/chipset95/maven/` right now!
